config/routes.rb
Rails.application.routes.draw do
	resources :lists do
		resources :columns, except: [:index, :show] do
			resources :items, except: [:index, :show]
		end
		resource :collaborator, only: [:create, :show, :destroy]
	end  
  
  devise_for :users
  resources :users
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :company
  has_many :columns, dependent: :destroy
  has_many :items, through: :columns
  has_many :user_lists, dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_company.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = current_user.lists
                        .includes(columns: :items)
                        .order('columns.id, items.position ASC')
                        .find(params[:id])
  end

  # GET /lists/new
  def new
    @list = current_company.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_company.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_company.lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:company_id, :name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.company_id %></td>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= content_tag :div, class: :row, data: {"list-channel-id": @list.id, controller: 'list-channel draggable'} do %>
	<% @list.columns.each do |column|%>
		<div class="col">
			<div class="card">
				<h5 class="card-title"><%= column.name %></h5>
				<div class="card-body">
					<%= content_tag :ul, class: 'card-text dropzone', id: dom_id(column), data: {id: column.id,  target: 'draggable.column'} do %>
						<%= render column.items, list: @list, column: column %>
					<% end %>
				</div>
				<%= link_to "New item", [:new, @list, column, :item ]%>
			</div>
		</div>
	<% end %>
<% end %>

<%= link_to "New column", [:new, @list, :column] %> |
<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

<br>
<br>

<%= form_with url: [@list, :collaborator], local: true do |form| %>
  <%= form.text_field :email %>
  <%= form.submit 'Invite Collaborator' %>
<% end %>

<%# link_to "Leave List", [@list, :collaborator], method: :delete if current_user.company_id != @list.company_id %>
<%= link_to "Leave List", [@list, :collaborator], method: :delete if current_user.invited_to_list?(@list) %>